### ISSUE TITLE
Does this library support Arduino Nano RP2040?

### ISSUE THREAD

**Issue by cenzwong** [adafruit/Adafruit_CircuitPython_WSGI#14]
Does this library support Arduino Nano RP2040? I see from the source and document saying that this library is for ESP32. Or does it have the Arduino Nano RP2040/Raspberry Pi Pico version?

**Comment by anecdata** [comment]
This was written to use the ESP32SPI library, which depends on an ESP32 wifi co-processor running NINA firmware. There are all-in-one versions of this hardware (e.g., PyPortal), or an ESP32 / "Airlift" wifi co-processor can be added to any MCU (with SPI and enough pins) running CircuitPython.

There are some other versions of HTTP servers for ESP32SPI and Espressif port of CircuitPython (e.g., ESP32-S2).

**Comment by dealerwrx** [comment]
Testing the rp2040, I have found that the WSGI library works when connected to the Mu editor (or the pc), but fails when running with only a power supply. I was attempting to use the Itsybitsy rp2040.
