### ISSUE TITLE
Dependency failure- unable to load 'adafruit_esp32spi.adafruit_esp32spi_socket'

### ISSUE THREAD

**Issue by tedivm** [adafruit/Adafruit_CircuitPython_WSGI#22]
```
Traceback (most recent call last):
  File "code.py", line 4, in <module>
  File "adafruit_wsgi/esp32spi_wsgiserver.py", line 36, in <module>
ImportError: no module named 'adafruit_esp32spi.adafruit_esp32spi_socket'
```

**Comment by dhalbert** [comment]
The library needs revision due to updates in ESP32SPI. See #21. Sorry.

**Comment by dhalbert** [comment]
If you are willing to update it that would be great. It's not a high priority for us right now, because we are thinking about further updates to ESP32SPI, e.g. https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/issues/203

**Comment by tedivm** [comment]
I'm already working on fixing it, but I think that compatibility ticket definitely makes the most sense.
